//
#ifndef INLAMNINGALGOS_DESIGNPATTERNS_EVENTCONSUMER_H
#define INLAMNINGALGOS_DESIGNPATTERNS_EVENTCONSUMER_H
#include "EventQueue.h"

void consumeEvent(EventQueue* queue);

#endif //INLAMNINGALGOS_DESIGNPATTERNS_EVENTCONSUMER_H
